[client] Disconnect QAbstractEventDispatcher::aboutToBlock when destroying ConnectionThread
build.kde.org detected a race when destroying the ConnectionThread.
Various destroy tests started to fail with a heap-use-after-free.
The pattern here is that in one thread the ConnectionThread is destroyed,
in the other thread we wait for an event. This turned out to be race with
one thread accessing already deleted memory.

Backtrace of the issue addressed here:
ERROR: AddressSanitizer: heap-use-after-free on address 0x606000021680 at pc 0x7f88716f210a bp 0x7fff0c4f49c0 sp 0x7fff0c4f49b0
READ of size 8 at 0x606000021680 thread T0
    #0 0x7f88716f2109 in operator() /home/jenkins/sources/kwayland/kf5-qt5/src/client/connection_thread.cpp:164
    #1 0x7f88716f466a in call /srv/jenkins/install/ubuntu/x86_64/g++/kf5-qt5/qt5/inst/usr/include/QtCore/qobjectdefs_impl.h:495
    #2 0x7f88716f43dd in call<QtPrivate::List<>, void> /srv/jenkins/install/ubuntu/x86_64/g++/kf5-qt5/qt5/inst/usr/include/QtCore/qobjectdefs_impl.h:552
    #3 0x7f88716f424f in impl /srv/jenkins/install/ubuntu/x86_64/g++/kf5-qt5/qt5/inst/usr/include/QtCore/qobject_impl.h:192
    #4 0x7f886ff8c362 in QtPrivate::QSlotObjectBase::call(QObject*, void**) ../../include/QtCore/../../src/corelib/kernel/qobject_impl.h:124
    #5 0x7f886ff88fe7 in QMetaObject::activate(QObject*, int, int, void**) kernel/qobject.cpp:3715
    #6 0x7f886ff888db in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) kernel/qobject.cpp:3595
    #7 0x7f8870033600 in QAbstractEventDispatcher::aboutToBlock() .moc/moc_qabstracteventdispatcher.cpp:138
    #8 0x7f886ffc8563 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) kernel/qeventdispatcher_glib.cpp:404
    #9 0x7f886ff406eb in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) kernel/qeventloop.cpp:128
    #10 0x7f886ff40a22 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) kernel/qeventloop.cpp:204
    #11 0x42fe04 in QTestEventLoop::enterLoopMSecs(int) /srv/jenkins/install/ubuntu/x86_64/g++/kf5-qt5/qt5/inst/usr/include/QtTest/qtesteventloop.h:99
    #12 0x430d3c in QSignalSpy::wait(int) /srv/jenkins/install/ubuntu/x86_64/g++/kf5-qt5/qt5/inst/usr/include/QtTest/qsignalspy.h:143
    #13 0x42ba11 in TestWaylandSurface::testDisconnect() /home/jenkins/sources/kwayland/kf5-qt5/autotests/client/test_wayland_surface.cpp:939
    #14 0x42c6b8 in TestWaylandSurface::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) /home/jenkins/sources/kwayland/kf5-qt5/build/autotests/client/test_wayland_surface.moc:142
    #15 0x7f886ff51858 in QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const kernel/qmetaobject.cpp:2211
    #16 0x7f886ff50bfb in QMetaObject::invokeMethod(QObject*, char const*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) kernel/qmetaobject.cpp:1478
    #17 0x7f8872e17240 in QMetaObject::invokeMethod(QObject*, char const*, Qt::ConnectionType, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) ../../include/QtCore/../../src/corelib/kernel/qobjectdefs.h:451
    #18 0x7f8872e12257 in qInvokeTestMethodDataEntry /home/jenkins/sources/qt5/kf5-qt5/qtbase/src/testlib/qtestcase.cpp:2040
    #19 0x7f8872e12b83 in qInvokeTestMethod /home/jenkins/sources/qt5/kf5-qt5/qtbase/src/testlib/qtestcase.cpp:2223
    #20 0x7f8872e13c2a in qInvokeTestMethods /home/jenkins/sources/qt5/kf5-qt5/qtbase/src/testlib/qtestcase.cpp:2568
    #21 0x7f8872e1441d in QTest::qExec(QObject*, int, char**) /home/jenkins/sources/qt5/kf5-qt5/qtbase/src/testlib/qtestcase.cpp:2964
    #22 0x42c18c in main /home/jenkins/sources/kwayland/kf5-qt5/autotests/client/test_wayland_surface.cpp:951
    #23 0x7f886f2f4a3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20a3f)
    #24 0x414118 in _start (/home/jenkins/sources/kwayland/kf5-qt5/build/autotests/client/testWaylandSurface+0x414118)

0x606000021680 is located 0 bytes inside of 64-byte region [0x606000021680,0x6060000216c0)
freed by thread T16 (QThread) here:
    #0 0x7f8871d56eaa in operator delete(void*) (/usr/lib/x86_64-linux-gnu/libasan.so.2.0.0+0x99eaa)
    #1 0x7f88716f687d in QScopedPointerDeleter<KWayland::Client::ConnectionThread::Private>::cleanup(KWayland::Client::ConnectionThread::Private*) (/home/jenkins/sources/kwayland/kf5-qt5/local-inst/srv/jenkins/install/ubuntu/x86_64/g++/kf5-qt5/frameworks/kwayland/inst/usr/lib/x86_64-linux-gnu/libKF5WaylandClient.so.5+0x1e987d)
    #2 0x7f88716f624d in QScopedPointer<KWayland::Client::ConnectionThread::Private, QScopedPointerDeleter<KWayland::Client::ConnectionThread::Private> >::~QScopedPointer() (/home/jenkins/sources/kwayland/kf5-qt5/local-inst/srv/jenkins/install/ubuntu/x86_64/g++/kf5-qt5/frameworks/kwayland/inst/usr/lib/x86_64-linux-gnu/libKF5WaylandClient.so.5+0x1e924d)
    #3 0x7f88716f23b0 in KWayland::Client::ConnectionThread::~ConnectionThread() /home/jenkins/sources/kwayland/kf5-qt5/src/client/connection_thread.h:120
    #4 0x7f88716f2445 in KWayland::Client::ConnectionThread::~ConnectionThread() /home/jenkins/sources/kwayland/kf5-qt5/src/client/connection_thread.h:120
    #5 0x7f886ff8ad5f in qDeleteInEventHandler(QObject*) kernel/qobject.cpp:4472
    #6 0x7f886ff8218e in QObject::event(QEvent*) kernel/qobject.cpp:1247
    #7 0x7f886ff44595 in QCoreApplicationPrivate::notify_helper(QObject*, QEvent*) kernel/qcoreapplication.cpp:1149
    #8 0x7f886ff441bf in doNotify kernel/qcoreapplication.cpp:1090
    #9 0x7f886ff44123 in QCoreApplication::notify(QObject*, QEvent*) kernel/qcoreapplication.cpp:1076
    #10 0x7f886ff440a0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) kernel/qcoreapplication.cpp:1015
    #11 0x7f886ff48389 in QCoreApplication::sendEvent(QObject*, QEvent*) ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:225
    #12 0x7f886ff45540 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) kernel/qcoreapplication.cpp:1650
    #13 0x7f886ff44ea5 in QCoreApplication::sendPostedEvents(QObject*, int) kernel/qcoreapplication.cpp:1508
    #14 0x7f886ffc7dda in postEventSourceDispatch kernel/qeventdispatcher_glib.cpp:270
    #15 0x7f886cf67ff6 in g_main_context_dispatch (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x49ff6)

previously allocated by thread T0 here:
    #0 0x7f8871d568b2 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2.0.0+0x998b2)
    #1 0x7f88716f224d in KWayland::Client::ConnectionThread::ConnectionThread(QObject*) /home/jenkins/sources/kwayland/kf5-qt5/src/client/connection_thread.cpp:160
    #2 0x416d2f in TestWaylandSurface::init() /home/jenkins/sources/kwayland/kf5-qt5/autotests/client/test_wayland_surface.cpp:102
    #3 0x42c380 in TestWaylandSurface::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) /home/jenkins/sources/kwayland/kf5-qt5/build/autotests/client/test_wayland_surface.moc:126
    #4 0x7f886ff51858 in QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const kernel/qmetaobject.cpp:2211
    #5 0x7f8872e185a0 in QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const (/srv/jenkins/install/ubuntu/x86_64/g++/kf5-qt5/qt5/inst/usr/lib/libQt5Test.so.5+0x195a0)
    #6 0x7f8872e0f9cc in invokeMethod /home/jenkins/sources/qt5/kf5-qt5/qtbase/src/testlib/qtestcase.cpp:1469
    #7 0x7f8872e12035 in qInvokeTestMethodDataEntry /home/jenkins/sources/qt5/kf5-qt5/qtbase/src/testlib/qtestcase.cpp:2027
    #8 0x7f8872e12b83 in qInvokeTestMethod /home/jenkins/sources/qt5/kf5-qt5/qtbase/src/testlib/qtestcase.cpp:2223
    #9 0x7f8872e13c2a in qInvokeTestMethods /home/jenkins/sources/qt5/kf5-qt5/qtbase/src/testlib/qtestcase.cpp:2568
    #10 0x7f8872e1441d in QTest::qExec(QObject*, int, char**) /home/jenkins/sources/qt5/kf5-qt5/qtbase/src/testlib/qtestcase.cpp:2964
    #11 0x42c18c in main /home/jenkins/sources/kwayland/kf5-qt5/autotests/client/test_wayland_surface.cpp:951
    #12 0x7f886f2f4a3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20a3f)

Thread T16 (QThread) created by T0 here:
    #0 0x7f8871cf36a3 in pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.2.0.0+0x366a3)
    #1 0x7f886fcf776e in QThread::start(QThread::Priority) thread/qthread_unix.cpp:618
    #2 0x416f54 in TestWaylandSurface::init() /home/jenkins/sources/kwayland/kf5-qt5/autotests/client/test_wayland_surface.cpp:108
    #3 0x42c380 in TestWaylandSurface::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) /home/jenkins/sources/kwayland/kf5-qt5/build/autotests/client/test_wayland_surface.moc:126
    #4 0x7f886ff51858 in QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const kernel/qmetaobject.cpp:2211
    #5 0x7f8872e185a0 in QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const (/srv/jenkins/install/ubuntu/x86_64/g++/kf5-qt5/qt5/inst/usr/lib/libQt5Test.so.5+0x195a0)
    #6 0x7f8872e0f9cc in invokeMethod /home/jenkins/sources/qt5/kf5-qt5/qtbase/src/testlib/qtestcase.cpp:1469
    #7 0x7f8872e12035 in qInvokeTestMethodDataEntry /home/jenkins/sources/qt5/kf5-qt5/qtbase/src/testlib/qtestcase.cpp:2027
    #8 0x7f8872e12b83 in qInvokeTestMethod /home/jenkins/sources/qt5/kf5-qt5/qtbase/src/testlib/qtestcase.cpp:2223
    #9 0x7f8872e13c2a in qInvokeTestMethods /home/jenkins/sources/qt5/kf5-qt5/qtbase/src/testlib/qtestcase.cpp:2568
    #10 0x7f8872e1441d in QTest::qExec(QObject*, int, char**) /home/jenkins/sources/qt5/kf5-qt5/qtbase/src/testlib/qtestcase.cpp:2964
    #11 0x42c18c in main /home/jenkins/sources/kwayland/kf5-qt5/autotests/client/test_wayland_surface.cpp:951
    #12 0x7f886f2f4a3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20a3f)